In [2]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int32')

In [7]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
a.dtype

dtype('float64')

In [10]:
a=np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
a.ndim  #返回数组的维度

2

In [12]:
a.shape  #表示各位维度大小的元组。返回的是一个元组

(2, 5)

# empty：产生随机数，并非空

In [5]:
a=np.empty((2,3,4))
a

array([[[ 1.66168655e+218,  1.43118707e-312,  2.59720465e+241,
          2.79466846e-310],
        [ 2.75849198e+055,  1.57972640e-312,  8.74601785e-308,
         -3.38460687e+125],
        [ 2.87521412e+161,  3.06561752e-313,  1.31388438e+169,
          2.13672446e+161]],

       [[ 2.17351068e+243, -2.12369850e+127,  1.14177894e+243,
          1.81022205e+060],
        [ 8.29824688e+016,  5.54152642e+257,  7.72658107e+274,
          6.52140396e-308],
        [ 1.33360308e+241,  4.04452398e-311,  7.91270162e-308,
          1.09385205e-303]]])

In [15]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a=np.arange(24).reshape(2,3,4) #可看成2个 3x4的数组
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a=np.arange(24).reshape(3,3,4)
a

ValueError: cannot reshape array of size 24 into shape (3,3,4)

In [48]:
np.linspace(0,10,100)  #0-10之间，产生100个均匀分布的数，最后一个不写的话，默认50个。

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [49]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [53]:
x=np.linspace(1,10)

In [55]:
y=np.sin(x)

In [56]:
a=np.array([1,2,3])
a.dtype

dtype('int32')

In [57]:
a=np.array([1,2,3],dtype=np.float32)
a.dtype

dtype('float32')

In [60]:
a=np.zeros(10,dtype=np.int32)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# numpy 数据类型

int_

int16
int32
int64
uint8 0-255 无符号整型,像素  处理图片
unit16 32 64

float_
float16 32 64

complex 64 128...

bool_ True False 布尔型

In [67]:
a=np.array([True,False,False,True])
a

array([ True, False, False,  True])

In [64]:
a.dtype

dtype('bool')

In [65]:
np.array(['sd','sd1'])

array(['sd', 'sd1'], dtype='<U3')

数据转换

In [69]:
a=np.array([True,False,False,True])
a

array([ True, False, False,  True])

In [70]:
a.astype(np.int16)

array([1, 0, 0, 1], dtype=int16)

In [72]:
a=np.array([1.1,2.3,3.4])
a

array([1.1, 2.3, 3.4])

In [78]:
a.dtype

dtype('float64')

In [81]:
a.astype(np.float16)

array([1.1, 2.3, 3.4], dtype=float16)

In [83]:
a.astype(np.int32)

array([1, 2, 3])