In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[2:8:2]  #(start:end:step)

array([2, 4, 6])

In [6]:
a2=arr[5:8]

In [7]:
a2

array([5, 6, 7])

In [10]:
a2[0]=100
a2

array([100,   6,   7])

In [11]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [12]:
a3=arr[5:8].copy()     #不改变全局

In [13]:
a3

array([100,   6,   7])

In [21]:
a3[1]=1000

In [22]:
a3

array([ 100, 1000,    7])

In [23]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

高维数组(适用：各种取数）

In [25]:
a4=np.arange(24).reshape(2,3,4)

In [26]:
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a4[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a4[1][1]

array([16, 17, 18, 19])

In [31]:
a4[1][1][2]

18

In [33]:
a4[0][2][1]=100

In [34]:
a4

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8, 100,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [40]:
a4[0][2][1]=100

In [39]:
a4[0,2,1]

100

In [44]:
a4[:,:1,:3]

array([[[ 0,  1,  2]],

       [[12, 13, 14]]])

In [45]:
a4[:,0,2]

array([ 2, 14])

In [50]:
a4[:,:,2:]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])

# 布尔索引

In [51]:
a=np.arange(20)

In [52]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [54]:
a[a>10]   #布尔取值

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
a[5<a<14]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
(a>5)&(a<14)

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [59]:
a[(a>5)&(a<14)]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [61]:
a[(a>5)&(a<14)&(a%2==0)]

array([ 6,  8, 10, 12])

In [62]:
a[(a<3)|(a>16)]

array([ 0,  1,  2, 17, 18, 19])

高维数组

In [65]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [66]:
a[(a>10)&(a%2!=0)]  #对高维数组处理，转变一维数组

array([11, 13, 15, 17, 19, 21, 23])

In [68]:
~(a<=10)         #取反

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [70]:
a[~(a<=10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])