In [1]:
import numpy as np

In [2]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a+10   # 1. array和标量值运算时，会广播到所有元素上

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a*100

array([[  0, 100, 200, 300, 400],
       [500, 600, 700, 800, 900]])

In [6]:
a+a # 2.相同形状数组

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [7]:
a*a

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [8]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a1=np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [11]:
a1.shape

(5,)

In [12]:
a.shape

(2, 5)

In [13]:
a+a1  # 3. 行为1，列相同，可与其运算

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [14]:
a2=np.arange(4)
a2

array([0, 1, 2, 3])

In [15]:
a2.shape

(4,)

In [16]:
a+a2

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [17]:
a3=np.arange(2)
a3

array([0, 1])

In [18]:
a3.shape

(2,)

In [19]:
a+a3

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [27]:
a3=np.arange(2).reshape(2,1)
a3

array([[0],
       [1]])

In [29]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
a+a3  # 4.列为1，行相同，可与其运算

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

数组转置

In [30]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a.shape

(2, 5)

In [33]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])