In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6],
       [7, 8]])

In [10]:
np.concatenate((a,b))  #合并

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.concatenate((a,b),axis=1)  # 轴 axis=1 沿着列合并，对列进行变化

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [12]:
np.concatenate((a,b),axis=0) #axis=0 沿着行合并，对行进行变化

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [17]:
np.concatenate((a1,a2))  #对于一维数组拼接，axis的值不影响最后的结果,默认情况下，axis=0可以不写

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.stack((a1,a2))  #stack 会增加维度

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
a1

array([1, 2, 3, 4])

In [24]:
np.append(a1,5)

array([1, 2, 3, 4, 5])

In [25]:
b

array([[5, 6],
       [7, 8]])

In [27]:
np.append(b,[9,10])  #不设置轴，append默认会降成一维数组。

array([ 5,  6,  7,  8,  9, 10])

In [29]:
np.append(b,[[9,10]],axis=0)    #添加二位数组，所以是[[]]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
np.append(b,[[9],[10]],axis=1) # 对列添加，第一行添加一个元素，第二行添加一个，所以要单独用[]

array([[ 5,  6,  9],
       [ 7,  8, 10]])

去重

In [32]:
a=np.array([1,2,1,2,3,4,5,6,7,2,3,6])

In [33]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])