In [1]:
import numpy as np

In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [6]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [7]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b=np.arange(10,0,-1)
b

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
np.maximum(a,b)

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])

In [15]:
a-b

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [16]:
np.subtract(a,b) # 可直接用a-b

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [18]:
a>=b

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
a[a>=b]

array([5, 6, 7, 8, 9])

# 统计方法

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.mean(a)  #均值

4.5

In [25]:
a.mean()  #对象方法

4.5

In [26]:
np.sum(a)

45

In [27]:
a.sum()

45

In [29]:
a1=a.reshape(2,5)

In [30]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a1.mean(axis=1) # 求每一行均值，沿着列计算

array([2., 7.])

In [32]:
np.mean(a1,axis=1)

array([2., 7.])

In [33]:
a1.mean(axis=0) # 求每一列均值，沿着行计算

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [34]:
a1.sum(0)  #axis=0, 列求和

array([ 5,  7,  9, 11, 13])

In [35]:
a1.sum(1)  #axis=1, 行求和

array([10, 35])

In [40]:
np.min(a1)

0

In [37]:
np.min(a1,axis=1)  # 每一行最小值

array([0, 5])

In [39]:
a1.min(1)

array([0, 5])

In [41]:
np.std(a1,axis=1) #每一行方差

array([1.41421356, 1.41421356])

In [43]:
np.median(a1,axis=1) #每一行中位值

array([2., 7.])

In [44]:
np.median(a1,axis=0) #每一列中位值

array([2.5, 3.5, 4.5, 5.5, 6.5])

众数

In [57]:
a2=np.array([1,2,3,4,4,5,6])
a2

array([1, 2, 3, 4, 4, 5, 6])

In [58]:
counts = np.bincount(a2) #方法一：统计非负整数的个数，不能统计浮点数
counts                   #bincount()函数返回的是固定的array[0, 1, 2, 3, ... , N]这个数据对应数字在该数组x中出现的次数。

array([0, 1, 1, 1, 2, 1, 1], dtype=int64)

In [59]:
np.argmax(counts)  #返回众数,argmax 函数就是用来求一个array中最大值下标

4

In [62]:
from scipy import stats   #方法二：可用于浮点数求众数
stats.mode(a2)[0][0]

4