In [1]:
import numpy as np

In [2]:
a=np.random.randn(10)

In [3]:
a

array([ 0.98234145,  0.14397603,  0.37081514, -2.10219464, -0.82524765,
       -0.11335591, -0.02018269,  0.67023692, -1.46311203, -0.29641394])

sort 排序

In [4]:
a.sort()  #最小到最大排序

In [5]:
a

array([-2.10219464, -1.46311203, -0.82524765, -0.29641394, -0.11335591,
       -0.02018269,  0.14397603,  0.37081514,  0.67023692,  0.98234145])

In [7]:
np.sort(a)  # 使用顶级方法，a 没有变化，需要赋值a=np.sort(a)

array([-2.10219464, -1.46311203, -0.82524765, -0.29641394, -0.11335591,
       -0.02018269,  0.14397603,  0.37081514,  0.67023692,  0.98234145])

In [9]:
a.shape=2,5

In [10]:
a

array([[-2.10219464, -1.46311203, -0.82524765, -0.29641394, -0.11335591],
       [-0.02018269,  0.14397603,  0.37081514,  0.67023692,  0.98234145]])

In [11]:
a.sort(axis=1)

In [12]:
a

array([[-2.10219464, -1.46311203, -0.82524765, -0.29641394, -0.11335591],
       [-0.02018269,  0.14397603,  0.37081514,  0.67023692,  0.98234145]])

In [13]:
a.sort?

argsort 排序,返回排序后的索引

In [14]:
a=np.array([2,4,1,3])

In [15]:
np.argsort(a)  # 最小值1的索引为2，其次2的索引为0， 3的索引为3, 4的索引为1

array([2, 0, 3, 1], dtype=int64)

In [16]:
np.argmax(a)  #返回最大值的索引

1

In [17]:
a

array([2, 4, 1, 3])

In [18]:
np.where(a>2)  #numpy.where() 返回满足条件的值的索引

(array([1, 3], dtype=int64),)

In [19]:
a[a>2]

array([4, 3])

In [20]:
a

array([2, 4, 1, 3])

In [21]:
b=np.array([9,5,6,7])
b

array([9, 5, 6, 7])

In [22]:
cond=np.array([True,False,False,False])  

In [27]:
np.where(cond,a,b)  #例：cond为True时从a中取值，cond为False时从b中取值。numpy.where (condition[, x, y]) 在以后大数据中，从两个选一个很有用

array([2, 5, 6, 7])

In [24]:
a

array([2, 4, 1, 3])

In [28]:
(a>2)

array([False,  True, False,  True])

In [30]:
(a>2).sum()  #布尔值，求满足条件的个数

2

In [31]:
sum(a>2)

2