In [1]:
import numpy as np

In [3]:
np.random.randn(10)  #生成正态分布随机数,未给定形状

array([-1.27160442,  0.83564471,  0.02889006, -1.93490543, -1.75674828,
       -1.50610911, -0.23146015,  0.13258477,  0.98932254, -1.03368641])

In [4]:
np.random.randn(3,4)

array([[ 4.27176055e-05, -9.84759841e-01, -4.14265251e-01,
         2.38748331e-01],
       [-1.75621940e-01,  1.08530789e+00, -2.27004338e-01,
        -8.92843834e-01],
       [ 4.45086381e-01, -1.32975033e+00, -1.47271915e+00,
         4.27682918e-01]])

In [6]:
np.random.normal(size=(3,4))

array([[-0.18073528, -2.00260796,  1.68877438,  0.43016979],
       [-0.53867204,  1.22668758, -1.52473213,  1.19553366],
       [-0.05412707, -2.24968213,  0.80129242,  0.24201689]])

In [7]:
np.random.randint(1,10,(3,4))  #随机自然数，最小值，最大值(不包含)，形状，[1,10)

array([[3, 1, 6, 3],
       [6, 9, 4, 3],
       [1, 5, 9, 2]])

In [11]:
a=np.array([2,4,1,3])
a

array([2, 4, 1, 3])

In [14]:
np.random.permutation(len(a))   #乱序，根据长度，生成一个乱序的索引

array([2, 3, 0, 1])

In [17]:
np.random.permutation(10)  #生成0-9乱序数值

array([8, 4, 1, 6, 5, 0, 7, 3, 2, 9])

In [19]:
np.random.choice([1,2,3,4,5,6])  #每一次运行，随机取一值，如抽奖，抽人名

3

In [27]:
np.random.choice([1,2,3,4,5,6],size=2) #随机选两个数

array([5, 2])

In [28]:
#伪随机数

In [29]:
np.random.seed(5)  # 每次生成随机数前使得每次产生相同的随机数

In [30]:
np.random.randn(3,4)

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651]])

In [31]:
np.random.seed(5) #产生随机数前都要重复一遍seed

In [32]:
np.random.randn(3,4)

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651]])

文件读写

In [33]:
a

array([2, 4, 1, 3])

In [34]:
np.save('lesson12',a)  #运行后即命名为lesson12保存到C:\用户\lenovo

In [43]:
np.load('lesson12.npy') # 恢复数据

array([2, 4, 1, 3])

In [45]:
np.savetxt('lesson2',a)

In [46]:
np.loadtxt('lesson2')

array([2., 4., 1., 3.])