In [1]:
import numpy as np

In [2]:
a=np.array([1.0,2.0,3])
b=np.array([[1,2,3],[4,5,6]],dtype=float)

In [3]:
a

array([1., 2., 3.])

In [4]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a.dtype

dtype('float64')

In [6]:
b.shape

(2, 3)

In [7]:
c=np.array([[1,2],[3,4]],dtype=complex)

In [8]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [9]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a1=np.arange(1,10,3,dtype=np.float)
a1

array([1., 4., 7.])

In [11]:
a2=np.zeros(2)
a2

array([0., 0.])

In [12]:
a2=np.zeros((2,2),dtype=int)
a2

array([[0, 0],
       [0, 0]])

In [13]:
a2=np.zeros((2,3,4))
a2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
a2.dtype

dtype('float64')

In [15]:
a2.shape

(2, 3, 4)

In [16]:
a2.ndim  #维度

3

In [17]:
a3=np.ones((2,3))

In [18]:
a3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a3=np.ones((2,3),dtype=int)
a3

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
a=np.empty(0)  #返回一个随机元素的矩阵
a

array([], dtype=float64)

In [21]:
a=np.empty(1)
a

array([5.98129748e-154])

In [22]:
a=np.empty(2)
a

array([3.69868021e-284, 2.03016870e-316])

In [23]:
a=np.empty((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
b=np.empty((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
a=np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [62]:
a.astype(np.int32)

array([ 1,  3,  5,  7, 10])

In [26]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
a=np.arange(1,20,2).reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [36]:
a=np.array([[2,3],[1,2],[1,2],[2,3]]).reshape(4,2)
a

array([[2, 3],
       [1, 2],
       [1, 2],
       [2, 3]])

In [37]:
a=np.zeros((2,3,4)).reshape(4,3,2)
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b=np.sin(a)
b

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [40]:
a=np.array([True,False,True,False])
a

array([ True, False,  True, False])

In [41]:
a.dtype

dtype('bool')

In [42]:
a.astype(np.int)  #改变数据类型

array([1, 0, 1, 0])

In [58]:
np.array(['sd','ssdd'])  #长度小于4的字符串类型

array(['sd', 'ssdd'], dtype='<U4')

数组切片

In [65]:
import numpy as np


In [66]:
a=np.arange(10)

In [67]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[4:8]

array([4, 5, 6, 7])

In [69]:
a[2:8:2]

array([2, 4, 6])

In [70]:
a[2]=100

In [71]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [75]:
a2=a[5:8].copy()   #copy() 深复制 a2变化 不会带来a的变化
a2

array([5, 6, 7])

In [76]:
a2[1]=1000
a2

array([   5, 1000,    7])

In [77]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [78]:
a3=np.arange(24).reshape(2,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
a3[0][1][2]

6

In [84]:
a3[0,1,2]

6

In [79]:
a3[0:1,0:1,0:1]

array([[[0]]])

In [80]:
a3[1:,2:3,3:]

array([[[23]]])

In [85]:
a3[0:1,0:2,:]

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [82]:
a3[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a3[a3>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [87]:
a3[0,1]

array([4, 5, 6, 7])

In [88]:
a3[0,1,0]

4

In [89]:
a3[1,2,3]

23

布尔索引

In [90]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [91]:
a[a>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [92]:
a>8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [93]:
(a>8)&(a<16)

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [94]:
a[(a>8)&(a<16)]

array([ 9, 10, 11, 12, 13, 14, 15])

In [95]:
a[(a>8)&(a<16)&(a%2==0)]

array([10, 12, 14])

In [96]:
a[(a<3)|(a>16)]  #或

array([ 0,  1,  2, 17, 18, 19])

In [97]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [99]:
a[(a>10)&(a%2!=0)]   #对高维数组布尔取值，转变一维数组

array([11, 13, 15, 17, 19, 21, 23])

In [100]:
a>10

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [103]:
~(a>=10)   #非运算，取反

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [104]:
a[~(a>=10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

数组的广播与转置

In [105]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [106]:
a+10

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [107]:
a*10

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [108]:
a+a

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [109]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [110]:
a.shape

(2, 3, 4)

In [111]:
a1=np.arange(4)
a1

array([0, 1, 2, 3])

In [112]:
a1.shape

(4,)

In [113]:
a+a1

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[12, 14, 16, 18],
        [16, 18, 20, 22],
        [20, 22, 24, 26]]])

In [114]:
a2=np.array([[0],[1],[2]])
a2

array([[0],
       [1],
       [2]])

In [115]:
a2.shape

(3, 1)

In [117]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [118]:
a+a2

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25]]])

In [ ]:
# 4种广播：与标量；相同形状；行相同、列为1；列相同、行为1

数组转置

In [123]:
a5=np.arange(3).reshape(1,3)
a5

array([[0, 1, 2]])

In [124]:
a5.T

array([[0],
       [1],
       [2]])

In [125]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [126]:
a+a5.T

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25]]])

数组合并与添加元素

In [179]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[0,1,2],[3,4,5]])
c=np.array([[2,2,2]])
d=np.array([[2],[2]])

In [180]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
a.shape

(2, 3)

In [182]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [183]:
d

array([[2],
       [2]])

In [184]:
a+b

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [185]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [186]:
np.concatenate((b,a))

array([[0, 1, 2],
       [3, 4, 5],
       [1, 2, 3],
       [4, 5, 6]])

In [187]:
np.concatenate((a,b),axis=1)   # 轴 axis=1 沿着列合并，对列进行变化

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5]])

In [188]:
np.concatenate((a,c))

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2]])

In [190]:
np.concatenate((a,d),axis=1)

array([[1, 2, 3, 2],
       [4, 5, 6, 2]])

In [191]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [192]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [193]:
np.concatenate((a1,a2),axis=0)   #对于一维数组拼接，axis的值不影响最后的结果,默认情况下，axis=0可以不写

array([1, 2, 3, 4, 5, 6, 7, 8])

In [140]:
np.stack((a1,a2))  #stack 会增加维度

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [199]:
c=np.stack((a,b))
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [200]:
c.ndim

3

In [141]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
a3=np.array([1,2,2,3])

In [142]:
np.concatenate((a1,a2,a3))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 2, 3])

In [143]:
b=np.stack((a1,a2,a3))
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 2, 3]])

In [144]:
b.ndim

2

In [145]:
np.append(a1,100)

array([  1,   2,   3,   4, 100])

In [146]:
np.append(b,[0,1,2,3])   #不设置轴，append默认会降成一维数组。

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 2, 3, 0, 1, 2, 3])

In [147]:
np.append(b,[[0,1,2,3]],axis=0) #添加二维数组，所以是[[]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 2, 3],
       [0, 1, 2, 3]])

In [148]:
np.append(b,[[0],[0],[0]],axis=1)

array([[1, 2, 3, 4, 0],
       [5, 6, 7, 8, 0],
       [1, 2, 2, 3, 0]])

In [149]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [150]:
a.ndim

3

In [151]:
b=a+10
b

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [152]:
np.concatenate((a,b))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [153]:
c=np.concatenate((a,b))
c.ndim

3

In [154]:
np.concatenate((a,b),axis=1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [155]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

去重

In [201]:
a=np.array([[1,2,1,3],[4,5,5,6]])
a

array([[1, 2, 1, 3],
       [4, 5, 5, 6]])

In [202]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [203]:
np.unique(a,axis=0)

array([[1, 2, 1, 3],
       [4, 5, 5, 6]])

In [208]:
np.unique(a,axis=1)

array([[1, 1, 2, 3],
       [4, 5, 5, 6]])

In [204]:
b=np.array([[1,2,1,3],[1,2,1,3]])
b

array([[1, 2, 1, 3],
       [1, 2, 1, 3]])

In [205]:
np.unique(b)

array([1, 2, 3])

In [206]:
np.unique(b,axis=0)

array([[1, 2, 1, 3]])

In [207]:
np.unique(b,axis=1)

array([[1, 2, 3],
       [1, 2, 3]])

通用函数

In [209]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [210]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [211]:
np.sum(a)

45

In [219]:
a.sum()

45

In [212]:
np.sum(a,axis=0) #求每一列的和

array([ 5,  7,  9, 11, 13])

In [213]:
np.sum(a,axis=1) #求每行的和，

array([10, 35])

In [214]:
np.max(a)

9

In [215]:
np.max(a,axis=0)

array([5, 6, 7, 8, 9])

In [216]:
np.max(a,axis=1)

array([4, 9])

In [217]:
np.median(a,axis=0) #中位值

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [218]:
a**2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

排序和搜索

In [220]:
a=np.random.randn(10)
a

array([ 1.14278515,  0.53341551, -1.11054829,  1.37030698,  1.21168564,
       -0.0686384 , -0.12577749, -1.20933078,  0.87974164,  0.77757859])

In [221]:
np.sort(a)

array([-1.20933078, -1.11054829, -0.12577749, -0.0686384 ,  0.53341551,
        0.77757859,  0.87974164,  1.14278515,  1.21168564,  1.37030698])

In [222]:
a.shape=2,5
a

array([[ 1.14278515,  0.53341551, -1.11054829,  1.37030698,  1.21168564],
       [-0.0686384 , -0.12577749, -1.20933078,  0.87974164,  0.77757859]])

In [223]:
np.sort(a)

array([[-1.11054829,  0.53341551,  1.14278515,  1.21168564,  1.37030698],
       [-1.20933078, -0.12577749, -0.0686384 ,  0.77757859,  0.87974164]])

In [224]:
np.sort(a,axis=0)  #每一列从小到大排序

array([[-0.0686384 , -0.12577749, -1.20933078,  0.87974164,  0.77757859],
       [ 1.14278515,  0.53341551, -1.11054829,  1.37030698,  1.21168564]])

argsort 排序,返回排序后的索引

In [225]:
a=np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
np.argsort(a) #argsort 排序,返回排序后的索引

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [233]:
np.argmax(a) #返回最大值的索引

7

In [234]:
a>5

array([False, False, False, False,  True,  True,  True,  True])

In [235]:
a[a>5]

array([6, 7, 8, 9])

In [236]:
np.where(a>5)  #返回满足条件的值的索引

(array([4, 5, 6, 7], dtype=int64),)

In [237]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [238]:
b=np.arange(10,5,-1)
b

array([10,  9,  8,  7,  6])

In [239]:
cond=np.array([True,False,False,True,False])
cond

array([ True, False, False,  True, False])

In [240]:
np.where(cond,a,b) #True时a, False为b

array([0, 9, 8, 3, 6])

In [241]:
np.where(a<3,a,b)

array([0, 1, 2, 7, 6])

In [242]:
a<3

array([ True,  True,  True, False, False])

In [243]:
a[a<3]

array([0, 1, 2])

In [244]:
a[a<3].sum()  #可检验有多少满足条件的值

3

In [245]:
np.sum(a<3)

3

随机数

random.rand()返回[0,1)之间的数

In [246]:
np.random.rand(1)

array([0.66780235])

In [248]:
np.random.rand(3)

array([0.16404832, 0.91767427, 0.43428053])

In [249]:
np.random.rand(2,2)

array([[0.97077836, 0.00820406],
       [0.77938837, 0.42384616]])

In [250]:
np.random.rand(2,2,3)

array([[[0.24089869, 0.47887781, 0.60730123],
        [0.88987721, 0.52147483, 0.65497359]],

       [[0.42099437, 0.81907956, 0.90193539],
        [0.2228527 , 0.05170805, 0.36186391]]])

np.random.randn(),用法同np.random.rand()一样，只是服从正态分布,标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）

In [251]:
a=np.random.randn(2,2)
a

array([[-0.91404181,  0.88035084],
       [-0.59732056, -0.43971948]])

np.random.normal(),也可以生成服从正态分布的随机值，不过这个函数可以指定均值是多少，方差为多少。
这个函数一共有三个参数，分别是（loc, scale, size），分别代表生成的高斯分布的随机数的均值、方差以及输出的size(想要输出多少个这个的值)

In [252]:
np.random.normal(size=10)

array([-1.71801934,  1.32069165,  0.93755203, -0.12083316,  0.96535443,
        0.98154433,  1.66653085,  0.44152716, -0.58658693, -0.6720895 ])

In [253]:
np.random.normal(size=(3,4))

array([[-0.19120903,  1.82641455,  0.49727303,  1.41626602],
       [-1.38929114, -0.91883333,  1.64350911, -0.12501967],
       [ 0.20612084,  0.14378031, -0.99626377, -1.0895722 ]])

np.random.randint()，通过low来指定起点，通过high来指定终点，通过size参数来指定数组的维度，通过dtype来确定类型。
numpy.random.randint(low, high=None, size=None, dtype=’l’)
1.返回随机整数，范围区间为[low,high），包含low，不包含high
2.参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
3.high没有填写时，默认生成随机数的范围是[0，low)

In [254]:
np.random.randint(1,5,size=5)

array([1, 2, 1, 4, 2])

In [255]:
np.random.randint(1,5)

4

In [256]:
np.random.randint(1,size=5)

array([0, 0, 0, 0, 0])

In [257]:
np.random.randint(1)

0

In [258]:
np.random.randint(1,5,size=(2,3))

array([[2, 2, 2],
       [4, 2, 4]])

np.random.random(size=None) ,通过size参数来指定维数生成[0,1)之间的浮点

In [260]:
np.random.random((2,2))

array([[0.71389829, 0.81199296],
       [0.77741294, 0.70232649]])

In [261]:
np.random.permutation(10)  #生成0-9乱序数值

array([1, 9, 2, 3, 6, 0, 5, 4, 7, 8])

In [262]:
np.random.permutation((2,3,4))  #生成乱序数值

array([3, 4, 2])

In [263]:
np.random.choice([1,2,3,4,5,6])  #每一次运行，随机取一值，如抽奖，抽人名

2

In [264]:
np.random.choice(['张','李','夏'])  #每一次运行，随机取一值，如抽奖，抽人名

'夏'

In [265]:
np.random.seed(5)    #每次运行代码时设置相同的seed，则每次生成的随机数也相同

In [266]:
np.random.randn(5)

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])

In [267]:
np.random.seed(5) 

In [268]:
np.random.randn(5)

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])

In [269]:
np.random.randn(5)

array([ 1.58248112, -0.9092324 , -0.59163666,  0.18760323, -0.32986996])

文件读写

In [270]:
a=np.array([1,2,3,3,4])

In [271]:
a

array([1, 2, 3, 3, 4])

In [272]:
np.save('lesson1',a)

In [273]:
np.load('lesson1.npy')

array([1, 2, 3, 3, 4])

In [274]:
np.savetxt('lesson3',a)

In [275]:
np.loadtxt('lesson3')

array([1., 2., 3., 3., 4.])

In [278]:
np.save(r'E:\3cschool\python_shuju_0\lesson22.npy',a)

In [283]:
np.load(r'E:\3cschool\python_shuju_0\lesson22.npy')

array([1, 2, 3, 3, 4])